### ISSUE TITLE
Error executing STB in Windows 10 and Python 3.8

### ISSUE THREAD

**Issue by gabimarti** [abirtone/STB#1]
When running STB on Windows 10 with Python 3.8 I get the following error message:

F:\DATA\test>stb -o test

   _____ _______ ____
  / ____|__   __|  _ \
 | (___    | |  | |_) |
  \___ \   | |  |  _ <
  ____) |  | |  | |_) |
 |_____/   |_|  |____/

 Security Tool Builder

[*] Requesting queries needed to build project:
Traceback (most recent call last):
  File "G:\Python\Python38\Scripts\stb-script.py", line 11, in <module>
    load_entry_point('stb==1.0.3', 'console_scripts', 'stb')()
  File "g:\python\python38\lib\site-packages\stb_lib\stb.py", line 57, in main
    run_console(config)
  File "g:\python\python38\lib\site-packages\stb_lib\api.py", line 35, in run_console
    responses = do_wizard()
  File "g:\python\python38\lib\site-packages\stb_lib\libs\wizard.py", line 48, in do_wizard
    questions = _load_questions()
  File "g:\python\python38\lib\site-packages\stb_lib\libs\wizard.py", line 33, in _load_questions
    return yaml.load(f.read())
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by cr0hn** [comment]
Related #2
